### ISSUE TITLE
Fatal error bei mehr als 7 Artikeln mit Veröffentlichungsdatum in der Zukunft

### ISSUE THREAD

**Issue by cookfirst** [PapooSoftware/PapooCMS#16]
Hallo,
werden zu einem Menüpunkt mehr als 7 Artikel veröffentlicht, deren "Erstellungsdatum" und damit das tatsächliche Anzeigedatum des Artikels in der Zukunft liegt, wird folgende Fehlermeldung geworfen. 
Wird die Anzahl der Veröffentlichungen dieser Artikel auf 7 reduziert, kommt dieser Fehler nicht mehr.

**Fatal error:** 
Uncaught TypeError: menu_class::urlencode(): Argument #1 ($url) must be of type string, null given, called in /www/htdocs/webseite/lib/classes/artikel_class.php on line 1095
 and defined in /www/htdocs/webseite/lib/classes/menu_class.php:1974 
 Stack trace: #0 /www/htdocs/webseite/lib/classes/artikel_class.php(1095):
  menu_class->urlencode(NULL) #1 /www/htdocs/webseite/lib/classes/artikel_class.php(120): 
  artikel_class->check_artikel() #2 /www/htdocs/webseite/all_inc_front.php(64): 
  artikel_class->make_inhalt() #3 /www/htdocs/webseite/index.php(17): 
  require_once('/www/htdocs/w00...') #4 {main} thrown in /www/htdocs/webseite/lib/classes/**menu_class.php on line 1974**

**Umgebungsinfos:**
Version ist: 23.04 Rev. 3bab4fe - Papoo Community
PHP Version 8.2.20 oder 8.3.8

**Comment by cz-papoo** [comment]
I could not reproduce the issue. However, the type error mentioned by the error message got fixed with commit e4a2cce.

Try the latest patch and check if the problem persists.

Note that the Papoo CMS is old software and doesn't receive regular updates anymore. If you receive any warnings using the latest commit of the `main` branch, try disabling PHP warnings and notices in the server configuration.
